### ISSUE TITLE
Make better main menu

### ISSUE THREAD

**Issue by tonikarppi** [pqbyte/temp-name-game#18]
Include buttons for start game and end game, not just a "press anywhere to continue".

**Comment by carllei** [comment]
Do we need an end game button in the main menu? That seems pointless. Maybe it is better if we just have that for the pause menu.

**Comment by tonikarppi** [comment]
Yeah, having an end game button might be pointless. But the menu does need to consist of buttons, though.

**Comment by tonikarppi** [comment]
Main menu is good enough
