### ISSUE TITLE
Add sound effects

### ISSUE THREAD

**Issue by carllei** [pqbyte/temp-name-game#26]
Add sound effects when a player shoots. Should we add a sound effect when a player is hit?

**Comment by tonikarppi** [comment]
https://freesound.org/ seems like a good place for sound effects. Find a "laser" sound effect for the shots, kinda like in Star Wars. A hit sound seems like a good idea too.

**Comment by carllei** [comment]
Planning on using this sound effect. https://freesound.org/people/bubaproducer/sounds/151022/

**Comment by tonikarppi** [comment]
:+1:

**Comment by carllei** [comment]
Added a retro explosion sound when hit.  https://freesound.org/people/jalastram/sounds/317750/

**Comment by tonikarppi** [comment]
Why did you close this? You haven't put up a pull request.

**Comment by tonikarppi** [comment]
:sound: #47
