### ISSUE TITLE
Add music

### ISSUE THREAD

**Issue by carllei** [pqbyte/temp-name-game#27]
Add music so that it plays during the game. We have to find suitable music that we have permission to use. Should the music play when one is in the main screen? Should we have a specific end of game music in the winner screen?

**Comment by tonikarppi** [comment]
http://incompetech.com/music/ seems like a good place to get royalty free music. Remember to write down the name and license of the one you choose.

**Comment by carllei** [comment]
Used this for the music. http://www.dl-sounds.com/royalty-free/8-bit-detective/

**Comment by tonikarppi** [comment]
:notes: #47
