### ISSUE TITLE
Add textures

### ISSUE THREAD

**Issue by carllei** [pqbyte/temp-name-game#28]
Add textures to the players, walls, and background. Do you have any specific preferences for the textures we are going to use?

**Comment by tonikarppi** [comment]
Black background, grey cube maybe?

**Comment by tonikarppi** [comment]
For sprites you can add color programmatically, so the red and blue players don't need their own textures.

**Comment by tonikarppi** [comment]
Still need textures for walls.

**Comment by carllei** [comment]
Working on the textures. It is proving more difficult than what I anticipated.

**Comment by tonikarppi** [comment]
If you want I can do the wall textures, and you can do the particles?

**Comment by carllei** [comment]
I will continue to work on the wall textures.

**Comment by tonikarppi** [comment]
Walls added in #57.
