### ISSUE TITLE
Write how to test the program in the README

### ISSUE THREAD

**Issue by tonikarppi** [pqbyte/temp-name-game#53]
Should say something like "Download Android Studio -> Run in emulator"

**Comment by macaullyjames** [comment]
Ideally there'd be an APK I can download and run too. Even better, put it in the Play store! That might be pushing it <48 hours before the deadline though :)

**Comment by tonikarppi** [comment]
I have a Play Store developer account, so I might as well do that.

**Comment by tonikarppi** [comment]
Or actually, I'll just upload the APK. Because of the Google review process, it takes some time for the app to become available on the store.

**Comment by macaullyjames** [comment]
They're usually pretty quick but it's probably a good idea to have a plan B, yes :)
