### ISSUE TITLE
Beautify the README!

### ISSUE THREAD

**Issue by macaullyjames** [pqbyte/temp-name-game#56]
Now that the game is (almost?) done it would be cool if you updated the README. How to download, screenshots, IGN reviews etc. You get the point :)

**Comment by tonikarppi** [comment]
Already on a branch. I'll merge when I can take screenshots, which is when the wall textures are done.

**Comment by macaullyjames** [comment]
Ah, great 👍

**Comment by tonikarppi** [comment]
Link to app will be put in README when available.
