### ISSUE TITLE
Restarting game starts another music instance

### ISSUE THREAD

**Issue by tonikarppi** [pqbyte/temp-name-game#63]
Need to close the previous instance when pressing restart.

**Comment by carllei** [comment]
I fixed it by disposing the music instance when the winner screen appears.

**Comment by tonikarppi** [comment]
The entire screen should actually be disposed, otherwise it's a memory leak.

**Comment by tonikarppi** [comment]
For some reason it's crashing, without a log output. I'm looking into it now.

**Comment by carllei** [comment]
Yh I disposed the whole screen. I called the dispose function.

**Comment by tonikarppi** [comment]
It's not crashing?

**Comment by carllei** [comment]
It is not crashing for me.

**Comment by tonikarppi** [comment]
Push it to a branch, I want to see

**Comment by tonikarppi** [comment]
Oh wait, it's not crashing for me anymore.

**Comment by carllei** [comment]
I pushed it to music-bug branch.

**Comment by tonikarppi** [comment]
Ok, you can create a pull request

**Comment by tonikarppi** [comment]
Fixed in #67
