### ISSUE TITLE
Create main menu

### ISSUE THREAD

**Issue by tonikarppi** [pqbyte/temp-name-game#7]
For starters, it could just consist of a "press to start" message.

**Comment by carllei** [comment]
I will create the start menu.

**Comment by carllei** [comment]
I have begun creating the start menu. There are some issues with importing font and some features from the Screen class like SetScreen.

**Comment by tonikarppi** [comment]
Did you get it working in the tutorial?

**Comment by carllei** [comment]
I am implementing a version of the tutorials so that it fits our project.
