### ISSUE TITLE
Create Pause Menu

### ISSUE THREAD

**Issue by carllei** [pqbyte/temp-name-game#8]
Create a pause menu. If someone exits the game or an interuption occurs, the pause menu will appear. It will contain a resume button.

**Comment by carllei** [comment]
I wiIl create the pause menu.

**Comment by carllei** [comment]
The pause menu will also contain an exit button.

**Comment by tonikarppi** [comment]
You might want to check out Scene2D for creating the menus, http://www.gamefromscratch.com/page/LibGDX-Tutorial-series.aspx part 9 (1-4). Basically, use the menu as the "scene" and the buttons as "actors". This is optional, but might be handy.

**Comment by carllei** [comment]
This seems very helpful. I will take a closer look at it.

**Comment by carllei** [comment]
I have implemented a basic version of the pause menu using similar code from the main menu. The problem is that it does not restart from where you left off.

**Comment by tonikarppi** [comment]
I can't help if you don't provide any information about your problem

**Comment by carllei** [comment]
The pause screen starts a new GameScreen when the program resumes. Therefore, a completely new game starts and the old one is erased. I have been trying to find ways to resume the current GameScreen but so far it has only caused the game to crash. I have been trying to run 
several screens concurrently and then using game.GameScreen.show(); but as I previously stated, it crashes the game.

**Comment by tonikarppi** [comment]
Check this link out. https://stackoverflow.com/questions/11466496/libgdx-game-how-to-display-pause-screen-when-user-click-on-pause-icon. Remember that when pressing the "back" button on android, the bottom left button, the game exits. Starting the game from that state should start the game from beginning. Pressing the home button (bottom-center) however, puts the application in the background. Android calls the "pause()" callback in that case, which is where you handle the pausing. You can then resume the game by pressing the bottom-right button and choosing the game.
